version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: devel
  ignore:
  - dependency-name: com.github.tomakehurst:wiremock
    versions:
    - "< 3, >= 2.a"
  - dependency-name: org.spockframework:spock-core
    versions:
    - "< 1.2-groovy-2.6, >= 1.2-groovy-2.5.a"
  - dependency-name: org.spockframework:spock-core
    versions:
    - ">= 1.3-groovy-2.a, < 1.4"
  - dependency-name: net.bytebuddy:byte-buddy
    versions:
    - 1.10.19
    - 1.10.20
    - 1.10.21
    - 1.10.22
  - dependency-name: junit:junit
    versions:
    - 4.13.1
  - dependency-name: com.netflix.nebula:nebula-test
    versions:
    - 7.10.2
  - dependency-name: ru.vyarus:gradle-animalsniffer-plugin
    versions:
    - 1.5.2
