version: "{branch} {build}"

build:
  verbosity: detailed

before_build:
  - SET PATH=%JAVA_HOME%\bin;%PATH%
  - java -version -Xmx32m

build_script:
  - gradlew.bat assemble -s

test_script:
  - gradlew.bat check funcTest -Pcompatibility -i -s --continue

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  - JAVA_HOME: C:\Program Files\Java\jdk9
  #Java 11 is not yet available for Windows executor
  - JAVA_HOME: C:\Program Files\Java\jdk10

matrix:
  fast_finish: false
