version: "{branch} {build}"

build:
  verbosity: detailed

before_build:
  - SET PATH=%JAVA_HOME%\bin;%PATH%
  - java -version -Xmx32m

build_script:
  - gradlew.bat assemble --stacktrace --no-daemon

test_script:
  - gradlew.bat check funcTest -Pcompatibility --stacktrace --no-daemon --continue

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.7.0
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

matrix:
  fast_finish: false
